### ISSUE TITLE
Issue for 0xbitx X d

### ISSUE THREAD

**Issue by 0183f** [0xbitx/dedsec_binaries#1]
Looks like you're so interested to decode/decrypt pyobsfucate codes ? 
Attempt it . It's the latest one ; )
https://github.com/RPW-ALEX1107GRAY/kyreen/blob/main/kyreen.py
https://github.com/RPW-ALEX1107GRAY/reve/blob/main/reve3.py

**Comment by 0xbitx** [comment]
![captured](https://github.com/user-attachments/assets/1fbee6f4-7f0c-457b-b71d-6d07a777cdf7)

**Comment by 0183f** [comment]
> ![captured](https://private-user-images.githubusercontent.com/74537225/370682121-1fbee6f4-7f0c-457b-b71d-6d07a777cdf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzI4OTEsIm5iZiI6MTcyNzI3MjU5MSwicGF0aCI6Ii83NDUzNzIyNS8zNzA2ODIxMjEtMWZiZWU2ZjQtN2YwYy00NTdiLWI3MWQtNmQwN2E3NzdjZGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEzNTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYzEzYzY5ZDQ2N2RkYWU0YTE1ZjBmZGEzZmMyZDAyMDlkOTQ5NjJkZjg3M2M5NmQzMDVmNmQ0NDdhM2UxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wx10sU9_cvTamsJdAFQ0EZq2PLWsnkErUSFS_xXqZJA)

Couldn't decrypt?

**Comment by 0xbitx** [comment]
not even running? fix it first

**Comment by 0183f** [comment]
> not even running? fix it first

Try kyreen first one

**Comment by 0183f** [comment]
> not even running? fix it first

Use Framework Crypto
